service:
  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "2"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    PG_HOST: 
    PG_PORT: 5432
    PG_DATABASE: 
    PG_USERNAME: 
    PG_PASSWORD: 
  
functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: product
          cors: true

  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: product/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true

  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: product
          method: post
          cors: true
