service:
  name: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters
  
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    QueueUrl: "${cf:product-service-${self:provider.stage}.SQSQueueUrl}"

  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:ListBucket"
     Resource:
       - "arn:aws:s3:::upload-files-shop-aws-course"
   - Effect: "Allow"
     Action:
       - "s3:*"
     Resource:
       - "arn:aws:s3:::upload-files-shop-aws-course/*"
   - Effect: "Allow"
     Action:
       - "sqs:*"
     Resource:
       - "${cf:product-service-${self:provider.stage}.SQSQueueArn}"

resources:
  Resources:
    GatewayResponse4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-allow-Methods: "'*'"
          gatewayresponse.header.Access-Control-allow-Credentials: "'true'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          authorizer:
            name: tokenAuthorizer
            arn: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:authorization-service-dev-basicAuthorizer"
            type: token
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: upload-files-shop-aws-course
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

